# Generated by Django 3.1.3 on 2020-11-15 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
