# Generated by Django 3.1.3 on 2020-11-17 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 6, 49, 9, 620486)),
        ),
    ]
